export interface SubscriptionPlan {
  id: string;
  name: string;
  displayName: string;
  description: string;
  price: {
    monthly: number;
    yearly: number;
  };
  features: {
    aiPhotos: number;
    aiModels: number;
    quality: 'low' | 'medium' | 'high' | 'ultra';
    likeness: 'low' | 'medium' | 'high' | 'ultra';
    parallelProcessing: number;
    commercialUse: boolean;
    importPhotos: boolean;
    customPrompts: boolean;
    photoRemix: boolean;
    photoEditing: boolean;
    photoCrop: boolean;
    photoZoom: boolean;
    aiVideos: boolean;
    loraSupport: boolean;
    photoRelight: boolean;
    unlimitedStorage: boolean;
    priorityProcessing: boolean;
    modelExport: boolean;
    freeAutoGenerated: number;
    watermark: boolean;
  };
  limits: {
    monthlyGenerations: number;
    concurrentGenerations: number;
    storageLimit: number; // in GB, -1 for unlimited
  };
  stripe: {
    productId?: string;
    monthlyPriceId?: string;
    yearlyPriceId?: string;
    metadata: Record<string, string>;
  };
  popular?: boolean;
  billingCycle: 'monthly' | 'yearly';
}

export const SUBSCRIPTION_PLANS: Record<string, SubscriptionPlan> = {
  starter: {
    id: 'starter',
    name: 'starter',
    displayName: 'Starter',
    description: 'Get started with basic AI photos, create your first model, and begin your AI photography journey.',
    price: {
      monthly: 9,
      yearly: 99 // 6+ months free
    },
    features: {
      aiPhotos: 50,
      aiModels: 1,
      quality: 'low',
      likeness: 'low',
      parallelProcessing: 1,
      commercialUse: false,
      importPhotos: false,
      customPrompts: false,
      photoRemix: false,
      photoEditing: false,
      photoCrop: false,
      photoZoom: false,
      aiVideos: false,
      loraSupport: false,
      photoRelight: false,
      unlimitedStorage: false,
      priorityProcessing: false,
      modelExport: false,
      freeAutoGenerated: 48,
      watermark: true
    },
    limits: {
      monthlyGenerations: 50,
      concurrentGenerations: 1,
      storageLimit: 1
    },
    stripe: {
      metadata: {
        plan_type: 'starter',
        model_type: 'flux_basic',
        quality_level: 'low',
        commercial_use: 'false'
      }
    },
    billingCycle: 'monthly'
  },
  pro: {
    id: 'pro',
    name: 'pro',
    displayName: 'Pro',
    description: 'Boost your creativity with higher quality photos, parallel processing, and commercial usage rights.',
    price: {
      monthly: 29,
      yearly: 349 // ~5 months free
    },
    features: {
      aiPhotos: 1000,
      aiModels: 3,
      quality: 'medium',
      likeness: 'medium',
      parallelProcessing: 4,
      commercialUse: true,
      importPhotos: true,
      customPrompts: true,
      photoRemix: true,
      photoEditing: false,
      photoCrop: false,
      photoZoom: false,
      aiVideos: false,
      loraSupport: false,
      photoRelight: false,
      unlimitedStorage: false,
      priorityProcessing: false,
      modelExport: false,
      freeAutoGenerated: 144,
      watermark: false
    },
    limits: {
      monthlyGenerations: 1000,
      concurrentGenerations: 4,
      storageLimit: 5
    },
    stripe: {
      metadata: {
        plan_type: 'pro',
        model_type: 'flux_standard',
        quality_level: 'medium',
        commercial_use: 'true'
      }
    },
    billingCycle: 'monthly'
  },
  premium: {
    id: 'premium',
    name: 'premium',
    displayName: 'Premium',
    description: 'Get more photos, more models, more features, and higher quality photos with our most popular plan.',
    price: {
      monthly: 49,
      yearly: 599 // ~6 months free
    },
    features: {
      aiPhotos: 3000,
      aiModels: 10,
      quality: 'high',
      likeness: 'high',
      parallelProcessing: 8,
      commercialUse: true,
      importPhotos: true,
      customPrompts: true,
      photoRemix: true,
      photoEditing: true,
      photoCrop: true,
      photoZoom: true,
      aiVideos: true,
      loraSupport: true,
      photoRelight: true,
      unlimitedStorage: false,
      priorityProcessing: true,
      modelExport: false,
      freeAutoGenerated: 2400,
      watermark: false
    },
    limits: {
      monthlyGenerations: 3000,
      concurrentGenerations: 8,
      storageLimit: 20
    },
    stripe: {
      metadata: {
        plan_type: 'premium',
        model_type: 'flux_hd',
        quality_level: 'high',
        commercial_use: 'true'
      }
    },
    popular: true,
    billingCycle: 'monthly'
  },
  ultra: {
    id: 'ultra',
    name: 'ultra',
    displayName: 'Ultra',
    description: 'Get our highest level of access with ultra-fast processing and enterprise-level performance.',
    price: {
      monthly: 99,
      yearly: 1199 // 6+ months free
    },
    features: {
      aiPhotos: 10000,
      aiModels: 50,
      quality: 'ultra',
      likeness: 'ultra',
      parallelProcessing: 16,
      commercialUse: true,
      importPhotos: true,
      customPrompts: true,
      photoRemix: true,
      photoEditing: true,
      photoCrop: true,
      photoZoom: true,
      aiVideos: true,
      loraSupport: true,
      photoRelight: true,
      unlimitedStorage: true,
      priorityProcessing: true,
      modelExport: true,
      freeAutoGenerated: 2400,
      watermark: false
    },
    limits: {
      monthlyGenerations: 10000,
      concurrentGenerations: 16,
      storageLimit: -1 // unlimited
    },
    stripe: {
      metadata: {
        plan_type: 'ultra',
        model_type: 'flux_hd',
        quality_level: 'ultra',
        commercial_use: 'true'
      }
    },
    billingCycle: 'monthly'
  }
};

export const PLAN_FEATURES_DISPLAY = {
  quality: {
    low: 'Low Quality Photos',
    medium: 'Medium Quality Photos',
    high: 'High Quality Photos',
    ultra: 'Ultra Quality Photos'
  },
  likeness: {
    low: 'Low Likeness',
    medium: 'Medium Likeness',
    high: 'High Likeness',
    ultra: 'Ultra-High Likeness'
  },
  parallelProcessing: {
    1: 'Take 1 photo at a time',
    4: 'Take up to 4 photos in parallel',
    8: 'Take up to 8 photos in parallel',
    16: 'Take up to 16 photos in parallel'
  } as Record<number, string>
};

export const BILLING_CYCLES = {
  monthly: {
    label: 'Monthly',
    discount: 0
  },
  yearly: {
    label: 'Yearly: get 6+ months free',
    discount: 0.5 // 50% discount (6 months free)
  }
};

// Helper functions
export function getPlanById(planId: string): SubscriptionPlan | undefined {
  return SUBSCRIPTION_PLANS[planId];
}

export function getPlansByBillingCycle(cycle: 'monthly' | 'yearly'): SubscriptionPlan[] {
  return Object.values(SUBSCRIPTION_PLANS).map(plan => ({
    ...plan,
    billingCycle: cycle,
    price: {
      monthly: plan.price.monthly,
      yearly: cycle === 'yearly' ? Math.round(plan.price.monthly * 12 * 0.5) : plan.price.yearly
    }
  }));
}

export function calculateYearlySavings(monthlyPrice: number): number {
  const yearlyPrice = Math.round(monthlyPrice * 12 * 0.5);
  const fullYearlyPrice = monthlyPrice * 12;
  return fullYearlyPrice - yearlyPrice;
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0
  }).format(amount);
}

export function getFeatureList(plan: SubscriptionPlan): string[] {
  const features: string[] = [];
  
  // Core features
  features.push(`${plan.features.aiPhotos.toLocaleString()} AI Photos (credits)`);
  features.push(`Create ${plan.features.aiModels} AI Model${plan.features.aiModels > 1 ? 's' : ''} per month`);
  features.push(`Flux™ ${plan.features.quality === 'high' || plan.features.quality === 'ultra' ? 'HD photorealistic' : 'photorealistic'} model`);
  
  // Quality and processing
  features.push(PLAN_FEATURES_DISPLAY.quality[plan.features.quality]);
  features.push(PLAN_FEATURES_DISPLAY.likeness[plan.features.likeness]);
  features.push(PLAN_FEATURES_DISPLAY.parallelProcessing[plan.features.parallelProcessing]);
  
  // Additional features
  if (plan.features.importPhotos) features.push('Import photos');
  if (plan.features.customPrompts) features.push('Write your own prompts');
  if (plan.features.photoRemix) features.push('Remix any photo');
  if (plan.features.commercialUse) features.push('Commercial use license');
  if (plan.features.photoEditing) features.push('Edit photos');
  if (plan.features.photoCrop) features.push('Crop photos');
  if (plan.features.photoZoom) features.push('Zoom out photos');
  if (plan.features.aiVideos) features.push('Shoot AI videos');
  if (plan.features.loraSupport) features.push('Use LoRas from Civitai');
  if (plan.features.photoRelight) features.push('Relight photos');
  if (plan.features.unlimitedStorage) features.push('Unlimited photo storage');
  if (plan.features.priorityProcessing) features.push('Priority: faster response times');
  if (plan.features.modelExport) features.push('Export your models');
  
  // Free photos
  const totalFreePhotos = plan.features.aiModels * plan.features.freeAutoGenerated;
  features.push(`For each model you create, you get ${plan.features.freeAutoGenerated} free photos (total ${totalFreePhotos.toLocaleString()} free photos) auto-generated`);
  
  return features;
}

export default SUBSCRIPTION_PLANS;
