name: Build and Deploy to Production

on:
  push:
    branches: [ "master" ] # Make sure this matches your main branch, e.g., "main" or "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Node.js
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # 3. Build BOTH applications
    - name: Build Backend & Frontend
      run: |
        npm install
        npm run build  # Build the backend (creates ./dist)
        cd frontend
        npm install
        CI=false npm run build # Build the frontend (creates ./frontend/build)

    # 4. Create the deployment package
    - name: Create Deployment Package
      run: |
        # Create the necessary directories for the package
        mkdir -p deploy-package/frontend

        # Copy backend files
        cp -R dist ./deploy-package/
        cp package.json ./deploy-package/
        cp package-lock.json ./deploy-package/
        cp ecosystem.config.js ./deploy-package/

        # Copy frontend files into the 'frontend' subdirectory
        cp -R frontend/build ./deploy-package/frontend/
        cp frontend/package.json ./deploy-package/frontend/
        cp frontend/package-lock.json ./deploy-package/frontend/

        # Compress the package
        tar -czf deploy-package.tar.gz -C deploy-package .

    # 5. Deploy the package to your server
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Upload the package to a temporary location
          scp -o StrictHostKeyChecking=no deploy-package.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy-package.tar.gz
          
          # On the server, extract the package and restart the app
          cd /var/www/realtyphotoai
          tar -xzf /tmp/deploy-package.tar.gz
          
          # Install production dependencies for both backend and frontend
          npm ci --omit=dev
          cd frontend
          npm ci --omit=dev
          cd ..

          # Fix permissions
          sudo chown -R www-data:www-data .
          
          # Reload the app with zero downtime
          pm2 reload ecosystem.config.js