name: Build and Deploy to Production

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Node.js
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # 3. Install dependencies and build BOTH apps
    - name: Install Dependencies & Build
      run: |
        npm install
        npm run build # Build the backend TS -> dist
        cd frontend
        npm install
        CI=false npm run build # Build the frontend React -> build

    # 4. Create the deployment package (the "artifact")
    - name: Create Deployment Package
      run: |
        cd ..
        mkdir deploy-package
        # Copy only the files needed for production
        cp -R dist ./deploy-package/
        cp -R frontend/build ./deploy-package/
        cp -R node_modules ./deploy-package/
        cp package.json ./deploy-package/
        cp package-lock.json ./deploy-package/
        cp ecosystem.config.js ./deploy-package/
        # Compress the package
        tar -czf deploy-package.tar.gz -C deploy-package .

    # 5. Deploy the package to your server
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Upload the package
          scp -o StrictHostKeyChecking=no deploy-package.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy-package.tar.gz
          
          # On the server, extract the package and restart the app
          cd /var/www/realtyphotoai
          # Extract over the old files, replacing them
          tar -xzf /tmp/deploy-package.tar.gz
          # Fix permissions just in case
          sudo chown -R www-data:www-data .
          # Reload the app with zero downtime
          pm2 reload ecosystem.config.js